package org.zerhusen.model.security;

public enum AuthorityName {
    ROLE_USER, ROLE_ADMIN, ROLE_ALERTS, ROLE_RULES, ROLE_HIERARICALMANAGEMENT,
    ROLE_CPP, ROLE_CONFIGURATION, ROLE_USERS, ROLE_CARD_TRANSACTIONS, ROLE_DASHBOARD
}